### ISSUE TITLE
question about  ReplaceArchive

### ISSUE THREAD

**Issue by txy960608** [Thealexbarney/XbTool#12]
I have edited common.bdat, and I want to use it replace the original file,my code is
`XbTool.exe -g xb2 -t ReplaceArchive -a bf2.arh bf2.ard -i  common.bdat -o common.bdat`

The first `common.bdat` is that I have edited,I think the second `common.bdat` is that the original file in 
bf2.ard

This is my first contact with such tools, could you please tell me where the error is？

Thank you

**Comment by Thealexbarney** [comment]
The `-o` option is the full path of the file being replaced in the archive

**Comment by txy960608** [comment]
Thank you for your answer
