### ISSUE TITLE
SaveEditor cannot load file

### ISSUE THREAD

**Issue by m0n4** [Thealexbarney/XbTool#14]
I was looking for a tool to modify XB1 saves but after a successful build of SaveEditor, the buttons are ineffective (open, load, write) and the PE is not available in the release section.

Can you give me some directions please or update the release section ?
Thanks in advance

_Build with VS 2019 on W7 32bits and W10 64bits, .net framework 4.6, .net core app 2.1/3_

**Comment by Thealexbarney** [comment]
The save editor is for Xenoblade 2 saves, not Xenoblade 1 saves
