### ISSUE TITLE
DecryptBdat doesn't decrypt (DE)

### ISSUE THREAD

**Issue by Mat37** [Thealexbarney/XbTool#15]
Hi,
i want to get the texts from DE which i believe are located in romfs\bdat\xx\script_msg_ms.bdat, so i used this command : 
XbTool -g xb2 -t DecryptBdat -i script_msg_ms.bdat -o output.txt but the resulting output.txt is exactly the same as the input file despite it saying "Finished decrypting". I also tried -g xb1 and even xbx but it always does the same.
Does it not support de or is it a bug ? Thanks in advance !

**Comment by ckurtz22** [comment]
It's possible your script_msg_ms.bdat is already decrypted.

**Comment by Mat37** [comment]
In fact i didn't compared the whole file, just the beginning and assumed the rest would be the same. Turns out i was wrong and the decryption worked.
