### ISSUE TITLE
Not an issue but a question.

### ISSUE THREAD

**Issue by princessblucy** [Thealexbarney/XbTool#19]
How would I go about editing the flags with the BDAT editor, or if impossible, editing the flags at all?

**Comment by Thealexbarney** [comment]
I don't think there's a way to automatically edit each flag. However, all the flags are backed by an actual field, so you'd have to edit that field.

**Comment by princessblucy** [comment]
how would i go about doing that?

**Comment by princessblucy** [comment]
Oh, I think I see it, it's just an unsigned byte near the rank column, correct?

**Comment by princessblucy** [comment]
Yeah that was exactly it, thank you.
