### ISSUE TITLE
Unable to edit Boolean Values in XC2 common.bdat

### ISSUE THREAD

**Issue by SoulBlast35** [Thealexbarney/XbTool#20]
Some tables have a bunch of Boolean values that the editor just displays as the word "Flag". The editor wont let you change them. For example, at the far right side of the table for Driver Arts, there are a bunch of Boolean values for "SArmour", "Normal" and "NoRepelled", which I can sort of guess what they all are. Is it possible to enable editing of these?

**Comment by Thealexbarney** [comment]
See https://github.com/Thealexbarney/XbTool/issues/19 for how to edit them

**Comment by SoulBlast35** [comment]
Thanks a ton! Sorry for not looking properly.
