### ISSUE TITLE
Issues using XbTool on xb1de .bdat

### ISSUE THREAD

**Issue by ShadowVolt** [Thealexbarney/XbTool#23]
Second Edit: So, I'm trying to use XbTool to extract the text from xb1de's bdat files, but I can't seem to get the command syntax to work. At first I was using the wrong game command, which I have since fixed (found via digging around in the code), ~~but now I'm getting a new weird error about some dictionary key? "System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary." I've tried to use the decryption feature, but it doesn't output anything, despite saying it was successful.~~

Isolated the cause of those issues, apparently since my files were from the updated version of the game, this program couldn't handle them. Made a fresh dump of the files without the update, solving that one. I'm now able to decrypt the .bdats, but none of the other output features work (eg. bdat2json).

Image of the terminal output with the ~~new~~ newer error attached below. dirs are relative to the .exe, same error with the full directory. the same error occurs on all ~~other valid tasks~~ bdat manupulation tasks  as well.

---

![Capture](https://user-images.githubusercontent.com/17579824/119265427-4fa64d80-bbac-11eb-9950-290c5fea80b3.PNG)

---

I'm trying to get a dump of the Japanese text from this game (also xb2 if possible) into a single file for research purposes, and I'm at a dead end on actually extracting it from the bdats. The BdatEditor can open them just fine, but that doesn't appear to have a way to export anything, and it would be far too tedious to copy it all manually line-by-line. I'm open to other options for getting this, but I have no idea how to do it myself, and I couldn't find anything aside from this program on the internet.

Possibly something like what is mentioned in #22 and #18 could work?

**Comment by Thealexbarney** [comment]
Make sure you have all the common bdats and bdats for a specific language in the same directory without any subdirectories or non-bdat files

**Comment by ShadowVolt** [comment]
Thanks, that let me use the bdat2json task. I should be able to get what I need out of these with some legwork. ~~It would be better for me if these were .csv,~~ but the other tasks all still throw errors.

Edit: Was able to convert it to a format I can use, I'm all set now. Also wanted to say thanks for making this toolset, couldn't have been easy to reverse those formats and assemble this.
